# View projections

In [83]:
import numpy as np

In [84]:
def projection(coeff):
    p = np.identity(4)
    p[3, 2] = -1/coeff
    return p

In [85]:
p = projection(3)

In [86]:
p

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -0.33333333,  1.        ]])

In [87]:
v = np.array([1, 2, 3])

In [88]:
v.shape

(3,)

In [95]:
np.append(v, 1)

array([1, 2, 3, 1])

In [98]:
p * np.append(v, 1)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0.,  3.,  0.],
       [ 0.,  0., -1.,  1.]])

In [99]:
np.dot(p, np.append(v, 1))

array([ 1.,  2.,  3.,  0.])

In [100]:
def viewport(x, y, w, h, depth):
    m = np.identity(4)
    m[0, 3] = x + w / 2.
    m[1, 3] = y + h / 2.
    m[2, 3] = depth / 2.

    m[0, 0] = w / 2.
    m[1, 1] = h / 2.
    m[2, 2] = depth / 2.
    return m

In [151]:
width = 800
height = 800
depth = 255
padding = 10
Viewport = viewport(0, 0, width, height, depth)
Viewport_padded = viewport(padding/2, padding/2, width - padding, height - padding, depth)
print("Viewport = ", Viewport)
print("Viewport_padded = ", Viewport_padded)

Viewport =  [[ 400.     0.     0.   400. ]
 [   0.   400.     0.   400. ]
 [   0.     0.   127.5  127.5]
 [   0.     0.     0.     1. ]]
Viewport_padded =  [[ 395.     0.     0.   400. ]
 [   0.   395.     0.   400. ]
 [   0.     0.   127.5  127.5]
 [   0.     0.     0.     1. ]]


In [160]:
v = [0.5, 0.5, 0.5]

In [161]:
[(v[0] + 1) * (width) / 2, (v[1] + 1) * (height )/2, (v[2]+1) * depth / 2]

[600.0, 600.0, 191.25]

In [162]:
[(padding + (v[0] + 1) * (width - padding)) / 2, (padding + (v[1] + 1) * (height - padding))/2, (v[2]+1) * depth / 2]

[597.5, 597.5, 191.25]

In [163]:
np.dot(Viewport, np.append(v, 1))[:3]

array([ 600.  ,  600.  ,  191.25])

In [164]:
np.dot(Viewport_padded, np.append(v, 1))[:3]

array([ 597.5 ,  597.5 ,  191.25])

In [165]:
p

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        , -0.33333333,  1.        ]])

In [166]:
np.dot(p, np.append(v, 1))

array([ 0.5       ,  0.5       ,  0.5       ,  0.83333333])

In [159]:
ViewProjection = np.dot(Viewport , p)
print(ViewProjection) 

[[  4.00000000e+02   0.00000000e+00  -1.33333333e+02   4.00000000e+02]
 [  0.00000000e+00   4.00000000e+02  -1.33333333e+02   4.00000000e+02]
 [  0.00000000e+00   0.00000000e+00   8.50000000e+01   1.27500000e+02]
 [  0.00000000e+00   0.00000000e+00  -3.33333333e-01   1.00000000e+00]]


In [167]:
np.dot(ViewProjection, np.append(v, 1))

array([ 533.33333333,  533.33333333,  170.        ,    0.83333333])